// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocpvbkgycdlprqxwvhmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jcHZia2d5Y2RscHJxeHd2aG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjUzNTYsImV4cCI6MjA2NDU0MTM1Nn0.qkMDXTZ2N6JksuVD8YTpsvsgzZq7jlDhaF9v7C8dDY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);